services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: csm_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - POSTGRES_URL=${POSTGRES_URL}
      - AUTH_SECRET=${AUTH_SECRET}
      - BASE_URL=http://91.245.72.34:3000
      - POSTIZ_API_KEY=${POSTIZ_API_KEY}
      - POSTIZ_BASE_URL=${POSTIZ_BASE_URL}
      - BLOTATO_PROFILES_URL=${BLOTATO_PROFILES_URL}
      - BLOTATO_API_KEY=${BLOTATO_API_KEY}
      - N8N_SUBMIT_FORM_WEBHOOK=${N8N_SUBMIT_FORM_WEBHOOK}
      - CSM_API_KEY=${CSM_API_KEY}
      - PUBLIC_BASE_URL=http://91.245.72.34:3000
      - NEXT_PUBLIC_BASE_URL=http://91.245.72.34:3000
    volumes:
      - ./uploads:/app/public/uploads
    networks:
      - csm_network
    command: >
      sh -c "
        echo 'Starting application...' &&
        npm start
      "

networks:
  csm_network:
    driver: bridge
